### PR TITLE
Add a page for the Prusa

### PR DESCRIPTION
**Pull request by sctv**
Add a page for the Prusa3 and a link to it from equipment.

### CODE REVIEW

**Comment by sctv** [comment]
[ERROR] In a non-interactive environment, it's necessary to set a CLOUDFLARE_API_TOKEN environment variable for wrangler to work. Please go to https://developers.cloudflare.com/fundamentals/api/get-started/create-token/ for instructions on how to create an api token, and assign its value to CLOUDFLARE_API_TOKEN.

**Comment by DanNixon** [comment]
You'll have to add a link to [`SUMMARY.md`](https://github.com/DanNixon/maker-space-wiki/blob/main/src/SUMMARY.md) too. Should have probably mentioned this, but it is a detail that would go into the eventual author docs.

**Comment by DanNixon** [comment]
> [ERROR] In a non-interactive environment, it's necessary to set a CLOUDFLARE_API_TOKEN environment variable for wrangler to work. Please go to https://developers.cloudflare.com/fundamentals/api/get-started/create-token/ for instructions on how to create an api token, and assign its value to CLOUDFLARE_API_TOKEN.

Accept the invite I sent and try again, I might have misunderstood the docs about collaborator access (i.e. you do not get access to secret variables even if the workflow is approved).

**Comment by sctv** [comment]
Have accepted the invite. Still fails.

**Comment by DanNixon** [comment]
Seems like access from forks is more effort than it is worth. Recreate the changes on a branch of this repository and open a new PR.

Eventually this will not be an issue as those who can edit the wiki will be expected to be members of https://github.com/MakerSpaceNewcastle.

**Pull request closed without merging**
